# Generated by Django 4.0.4 on 2022-05-24 19:10

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='course_image'),
        ),
    ]
